services:
  db:
    image: postgres:15-alpine
    # platform: linux/arm64/v8 #If you are on MacOS you need to uncomment this line
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: python:3.9-slim-bullseye
    # platform: linux/arm64/v8 #If you are on MacOS you need to uncomment this line
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"
    volumes:
      - ./:/app
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://app:postgres@db:5432/app
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - JWT_SECRET_KEY=supersecretkey
      # (Opcional) manter também DATABASE_URL se seu código usa:
      - DATABASE_URL=postgresql://app:postgres@db:5432/app

volumes:
  postgres_data:
    name: myapp-postgres-data