

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: python:3.9-slim
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"
    # tty: true
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://app:postgres@db:5432/app
      - JWT_SECRET_KEY=supersecretkey